name: landmark_records
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  provider: ^6.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  flutter_map_marker_cluster: ^1.3.6
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
